name: "Changelog Query"
description: "Validate the changelog file and extract current release information"
inputs:
  prompt:
    description: >
      The prompt(s) to generate completions for, encoded as a string, array of strings, array of tokens, or array of token arrays.
      Note that <|endoftext|> is the document separator that the model sees during training, so if a prompt is not specified the model will generate as if from the beginning of a new document.
    required: true
  max_tokens:
    description: "The maximum number of tokens to generate in the completion."
    default: "64"
    required: false
  temperature:
    description: "What sampling temperature to use. Higher values means the model will take more risks. Try 0.9 for more creative applications, and 0 (argmax sampling) for ones with a well-defined answer."
    required: false
  top_p:
    description: "An alternative to sampling with temperature, called nucleus sampling, where the model considers the results of the tokens with top_p probability mass. So 0.1 means only the tokens comprising the top 10% probability mass are considered."
    required: false
  n:
    description: "How many completions to generate for each prompt."
    required: false
  stream:
    description: "Whether to stream back partial progress. If set, tokens will be sent as data-only server-sent events as they become available, with the stream terminated by a data: [DONE] message."
    required: false
  logprobs:
    description: "Include the log probabilities on the logprobs most likely tokens, as well the chosen tokens. For example, if logprobs is 5, the API will return a list of the 5 most likely tokens. The API will always return the logprob of the sampled token, so there may be up to logprobs+1 elements in the response."
    required: false
  echo:
    description: "Echo back the prompt in addition to the completion"
    required: false
  stop:
    description: "Up to 4 sequences where the API will stop generating further tokens. The returned text will not contain the stop sequence."
    required: false
  presence_penalty:
    description: "Number between -2.0 and 2.0. Positive values penalize new tokens based on whether they appear in the text so far, increasing the model's likelihood to talk about new topics."
    required: false
  frequency_penalty:
    description: "Number between -2.0 and 2.0. Positive values penalize new tokens based on their existing frequency in the text so far, decreasing the model's likelihood to repeat the same line verbatim."
    required: false
  best_of:
    description: 'Generates best_of completions server-side and returns the "best" (the one with the lowest log probability per token). Results cannot be streamed.'
    required: false
  logit_bias:
    description: "Modify the likelihood of specified tokens appearing in the completion."
    required: false

outputs:
  response:
    description: "The completion response for the provided prompt and parameters"
runs:
  using: "node12"
  main: "index.js"
branding:
  icon: "activity"
  color: "green"
