name: "OpenAI Issue Labeler"
on:
  issues:
    types: [opened, edited]

jobs:
  openai_completion_job:
    runs-on: ubuntu-latest
    name: OpenAI
    steps:
      - name: Dump GitHub context
        id: github_context_step
        run: echo '${{ toJSON(github) }}'
      - uses: actions/checkout@v2
      - uses: ./
        name: OpenAI Completion
        id: openai_completion
        with:
          prompt: 'Given the Possible Labels "database,api,ui,help,critical,permission,feature,bug,cleanup,algo,funny,idea" what are the best 3 labels for "${{ github.event.issue.title }}" and "${{ github.event.issue.body }}" in a csv list?'
          max_tokens: 5
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - uses: actions/github-script@v5
        name: Print the response text
        with:
          debug: true,
          script: |
            const text = JSON.parse('${{ steps.openai_completion.outputs.response }}').choices[0].text
            await github.rest.issues.addLabels({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.payload.issue.number,
              labels: text.split(',').map(l => l.trim()).filter(l => l.length > 0)
            });
