name: "OpenAI Issue Labeler"
on:
  issues:
    types: [opened, edited]

jobs:
  openai_completion_job:
    runs-on: ubuntu-latest
    name: OpenAI
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        name: OpenAI Completion
        id: openai_completion
        with:
          prompt: |
            Title: ${{ github.payload.title }}
            Body: ${{ github.payload.issue.body }}
            Possible Labels: database,api,ui,needs help,critical,permission,new feature,bug,cleanup
            Given the possible labels what are the best labels for the Tile and Body in a csv list?
          max_tokens: 5
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}

      - uses: actions/github-script@v5
        name: Print the response text
        with:
          script: |
            const text = JSON.parse('${{ steps.openai_completion.outputs.response }}').choices[0].text
            await github.rest.issues..addLabels({
              owner: github.context.repo.owner,
              repo: github.context.repo.repo,
              issue_number: issue_number,
              labels: text.split(',').map(l => l.trim())
            });
